### ISSUE TITLE
Does this only record YAML or it can actually assert something?

### ISSUE THREAD

**Issue by littlepea** [YPlan/django-perf-rec#18]
In all the examples and the blog post, I can't see any asserts, only recording... How can this actually be used to build test cases and assert based on the performance records? (like `numQueries`)

**Comment by adamchainz** [comment]
It automatically asserts on the second-plus runs. Maybe `record()` could be called something more explicit like `record_and_assert()`?

**Comment by adamchainz** [comment]
Also we could add an example of a failing test to the README

**Comment by littlepea** [comment]
I think it would be useful to document what does it assert exactly? Is it that the number of queries from the previous saved yaml file is not smaller than the current/new one? Does it mean that the very first recording sets the "acceptable baseline"? What if number of queries had increased but it's on purpose (added more functionality on a page)?

In the README I can't find how the passing criteria are defined and is it controlled by the user...

**Comment by adamchainz** [comment]
It just checks that they're exactly the same, anything else is a failure. Will document!

**Comment by adamchainz** [comment]
> Then if you re-run the test and the performance record doesn't match, the test will fail.

This kind of says it, but you're right that it could be clarified

**Comment by littlepea** [comment]
So how is the baseline set? If there's no existing record, then record and PASS, if there is a record and it's the same also PASS, if there is a record and it's different then FAIL?

What if it's different but on purpose? I should delete the YAML file and rerun to PASS?

**Comment by adamchainz** [comment]
Yes that's exactly the workflow we use. I'll improve the README later.
