### ISSUE TITLE
Duplicated performance records when running tests again

### ISSUE THREAD

**Issue by njoyard** [YPlan/django-perf-rec#28]
When running tests multiple times in the same environment, the `__file__` global points to `.pyc` files when they are present, so `utils.current_test()` picks them up instead of source files.

The fix is quite straightforward of course, should I include it in #27 or make a new PR (that will have a merge conflict) ?

**Comment by adamchainz** [comment]
Aha! I never found this because we run our test/dev environment with pyc files disabled.

New PR please, I can handle merge conflicts 👍

**Comment by adamchainz** [comment]
Fixed in 6a34df3ef13c71c7fa11a6ff0443a3d9c10ba619
