### ISSUE TITLE
Session keys not mangled in performance files

### ISSUE THREAD

**Issue by njoyard** [YPlan/django-perf-rec#32]
Session keys in django are generated by taking 32 random chars in `string.ascii_lowercase + string.digits` (see [django.contrib.sessions.backends.base](https://github.com/django/django/blob/stable/1.10.x/django/contrib/sessions/backends/base.py#L163)), however this pattern is not mangled by regexes in `django_perf_rec.cache.CacheOps.VARIABLE_RES̀`.

Should we add `/\b[0-9a-z]{32}\b/` to the list ? That seems acceptable to me as 32-letter column/table/variable without underscores or uppercase letters should not be very frequent.

**Comment by adamchainz** [comment]
Sounds good!

**Comment by adamchainz** [comment]
Fixed by #33
